import { Download, QrCode } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

type QrCodeCardProps = Readonly<{
  assetId: string;
  qrUrl: string;
}>;

export function QrCodeCard({ assetId, qrUrl }: QrCodeCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <QrCode aria-hidden="true" className="size-5" />
          QR Code
        </CardTitle>
        <CardDescription>เปิด Public Asset Lookup</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Generated by an authenticated server route; no QR file is stored. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          alt={`QR code for ${qrUrl}`}
          className="mx-auto size-56 rounded-lg border bg-white p-3"
          src={`/api/assets/${assetId}/qr?format=svg`}
        />
        <p className="text-muted-foreground text-xs break-all">{qrUrl}</p>
        <div className="flex gap-2">
          <Button asChild variant="outline">
            <a download href={`/api/assets/${assetId}/qr?format=png`}>
              <Download aria-hidden="true" className="size-4" />
              PNG
            </a>
          </Button>
          <Button asChild variant="outline">
            <a download href={`/api/assets/${assetId}/qr?format=svg`}>
              <Download aria-hidden="true" className="size-4" />
              SVG
            </a>
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
